### ISSUE TITLE
Theme created with python transparentpanel.py doesn't always have transparent panel

### ISSUE THREAD

**Issue by SteveKej** [psifidotos/plasma-transparent-panel#1]
Hi,

As I mentioned at /www.kde-look.org  I'm having some issues with the transparentpanel.py script.

Firstly, newly created themes don't have the transparent panel at first, but running the script a second time, or disabling and re-enabling compositing will make the selected panel transparent.

Secondly the selected panel isn't transparent after logout/login but regains transparency after toggling compositing.  I suppose these issues are related.

This is what I did:
I removed all themes from ~/.local/share/plasma/desktoptheme/ and then cleared all theme related files from ~/.cache/
Then ran the script:

```
┌─[steve@arch][~]
└─[$]> cd Downloads
┌─[steve@arch][Downloads]
└─[$]> python transparentpanel.py --list
['default', 'breeze-light', 'air', 'breeze-dark', 'oxygen']
[]
┌─[steve@arch][Downloads]
└─[$]> python transparentpanel.py breeze-dark South
main theme: breeze-dark
Disabled Shadows
top
topleft
topright
left
right
┌─[steve@arch][Downloads]
└─[$]> 
```

So it looks ok there but the bottom panel wasn't transparent until I did the further actions described above.

Unfortunately I can't try the MX theme as I don't have a copy and the theme's creator doesn't have any files marked as active to download on kde-look.  I left a message about that there a little while ago.  I tested with the KArc-Transparent theme and the panel was transparent at login, so no problems there.

Please let me know if there's any other info that could help.

**Comment by SteveKej** [comment]
Well I just got an update for my frameworks packages to 5.25.0 and this seems to have solved the issue :)  I'll see how it goes for the next few days and report back if there are any developments.

Thank you!

**Comment by psifidotos** [comment]
Ok... :-)

**Comment by SteveKej** [comment]
Ok I've rebooted a number of times now and there have been no further problems, so I guess we can close this.

**Comment by psifidotos** [comment]
There are cases that the script broke the widgets/panel-background.svgz file in which all the magic was happening... For exaple in SlimGlow theme and in Oxygen for specific shadows enablement/disablement..

I am going to update the script internals in order to handle also these cases...

**Comment by psifidotos** [comment]
this is fixed in new version....
