### ISSUE TITLE
The gui for transparent panel doesn't scale properly to fit the desktop resolution

### ISSUE THREAD

**Issue by SteveKej** [psifidotos/plasma-transparent-panel#2]
When I run trasparent.sh (typo there btw - missing 'n') The resulting gui is too large vertically to fit on my desktop (1366x768).  I need to alt+left click and move the window above the desktop, then resize it lower to see the bottom of the window.  More importantly the "Generate New Theme" button can't be seen:
![image](https://cloud.githubusercontent.com/assets/1503819/18030744/0745cbf0-6cbb-11e6-98a7-c18b1827709d.png)

**Comment by psifidotos** [comment]
Oh.... I must scale it down !!!!

**Comment by psifidotos** [comment]
I scaled it down... It must be ok now...
