### ISSUE TITLE
All panel transparent 

### ISSUE THREAD

**Issue by Albertojer** [psifidotos/plasma-transparent-panel#3]
Hi! 
Thanks for your work. Great plasmoid!
The script does not work well with Minimalistic theme (you can find it on kde-look). I used it as

python transparentpanel.py Minimalistic South

and the new theme has ALL panel transparent. How can I fix it?
Thank you!

**Comment by psifidotos** [comment]
@Albertojer thank u !!!

I fixed it for you in master :-), it was a case that the script didnt catch it... I think it's ok now...

Instead of the command line for easiness you can use directly the gui...
click on "transparent.sh" it is a python gui...

**Comment by psifidotos** [comment]
@Albertojer Oh!!!! 
And if it works for you.. Close please this issue!!!

thank u !!!

**Comment by Albertojer** [comment]
It works perfectly. Thank you!
