### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by MarianArlt** [psifidotos/plasma-transparent-panel#4]
I'm on latest KDE Neon User with Plasma 5.8 and the script throws an error, finishes its task but the resulting theme won't apply transparency:

`kbuildsycoca5 running...`

`Recreating ksycoca file ("/home/marian/.cache/ksycoca5_en_R0X_3FjFX5krBG2blXk_nJ8NqDU=", version 303)`

`Menu "applications-kmenuedit.menu" not found.`

`The desktop entry file "/usr/share/applications/display-im6.desktop" has Type= "Application" but no Exec line`

`kf5.kservice.sycoca: Invalid Service :  "/usr/share/applications/display-im6.desktop"`

`The desktop entry file "/usr/share/applications/display-im6.q16.desktop" has Type= "Application" but no Exec line`

`kf5.kservice.sycoca: Invalid Service :  "/usr/share/applications/display-im6.q16.desktop"`

**Comment by psifidotos** [comment]
I think this is not a problem... these are plasma warnings..
Try  to disable from plasma's system settings the following **Desktop Effects** :
- Blur
- Background Contrast

**Comment by MarianArlt** [comment]
Spot on! Although it removes the top panel shadows which some people may want to preserve. In my case I actually was searching how to disable it. Hahaha! So it's two wins for me! Thank you.

**Comment by psifidotos** [comment]
:+1: 

@MarianArlt if you use the **transparent.sh** GUI you can choose easily which shadows to show/hide in the new theme...

**Comment by MarianArlt** [comment]
Aaah nice, it wasn't clear to me what those shadows refer to! I actually thought it was the shadows of the transparent panel. (Who'd want that anyway, right?)

**Comment by psifidotos** [comment]
;)

**Comment by RafaAguilar** [comment]
In my scenario, I had to disable the two mentioned effects, but I want to disable blur only in new South Panel. this can be done?, if so, how?

**Comment by psifidotos** [comment]
> In my scenario, I had to disable the two mentioned effects, but I want to disable blur only in new South Panel. this can be done?, if so, how?

unfortunately this can be done only in Plasma 5.9, in which you dont need at all the trasparent panel script and you can keep both blur and background contrast effects

**Comment by psifidotos** [comment]
> In my scenario, I had to disable the two mentioned effects, but I want to disable blur only in new South Panel. this can be done?, if so, how?

by reading again your question, do you mean that you need to keep also background contrast for the Now Dock?
