### ISSUE TITLE
Request for CLI option to disable specific shadows (or all shadows)

### ISSUE THREAD

**Issue by AndydeCleyre** [psifidotos/plasma-transparent-panel#5]
I use a transparent East panel, but I have a non-transparent top panel, centered, which does not span the whole width of the screen. So it would be nice to get a CLI (non-interactive) way to disable all shadows, as otherwise there's an awkward shadow at the right and bottom-right of this top panel.

Thanks again for this project!

**Comment by psifidotos** [comment]
> it would be nice to get a CLI (non-interactive) way to disable all shadows, as otherwise there's an awkward shadow at the right and bottom-right of this top panel.
- the gui way is to run **transparent.sh** and the third step in the window is to show/hide any shadows you want
- the command way is to use:
  `python transparentpanel.py <theme-name> East right bottomright`

**Comment by AndydeCleyre** [comment]
According to the readme, and in accordance with my experience, that command _shows_ shadows at the right and bottomright, while I need to do the opposite.

**Comment by psifidotos** [comment]
you could try then:
`python transparentpanel.py <theme-name> East !right !bottomright`

**Comment by psifidotos** [comment]
small type mistake the correct is:
`python transparentpanel.py <theme-name> East -right -bottomright`

**Comment by AndydeCleyre** [comment]
Thanks!
